[YB-71] 나라 선택 화면 UI 구현
YAPP-Github/YeoBee-iOS pull request #18
Opened 2023-12-31 09:38 UTC by devjoonn

## 이슈번호
[YB-71]

## 수정 사항
- 여행 등록(TravelRegistration) Feature를 생성했습니다.
- DesignSystem에 YBPaddingButton을 추가했습니다. [전체, 유럽, 아시아 등등] 카테고리 버튼으로 쓰이는데 제리가 구현하고 있으신 개인예산 화면의 "추가" 버튼에도 쓰일 수 있을 것 같습니다. 지금은 .medium 기본값으로 쓰고 있는데 "추가" 버튼에 쓰이려면 padding 조절이 필요할 것 같아요!
- 나라 선택 화면에서 cell 부분에 체크 버튼, 비활성화 체크 버튼, 원형 삭제 버튼 이미지 추가했습니다.

## 화면 (Optional)
| 일반 | 선택 |
| --- | --- |
|<img width="431" alt="스크린샷 2023-12-31 오후 6 11 08" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/5e6c7e6e-325f-49e1-972d-3a46497b4ee6"> | <img width="431" alt="스크린샷 2023-12-31 오후 6 11 18" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/bc8444d6-6dc1-4d5b-b34c-b1eefbcf959d">|

| 선택 삭제 | 레이아웃 변경 |
| --- | --- |
|<img width="431" alt="스크린샷 2023-12-31 오후 6 11 08" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/83294eb9-a787-4599-87d8-b4c7dcdaa077"> | <img width="431" alt="스크린샷 2023-12-31 오후 6 11 18" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/a1e51157-9d9e-4b58-a61f-6d9853d70d3a">|

## target module
TravelRegistration

## 참고사항
 - DesignSystem에 YBTextButton으로 "다음으로 버튼"을 만들었는데 피그마상에서 색상과 조금 다른 것 같습니다!
 - YBTextButton에서 setAppearance를 변경하게 될 시 버튼 title도 날라가서 임의로 title 지정해두었습니다. (CountryViewController에서 bindState 부분)

2023-12-31 10:45 UTC, llghdud921 requested changes
현준님! 너무 고생많으셨습니다~!

현준님 구현 방식보고 dataSource가 reactor가 가지고 있는 것이 맞는건지 고민이 되네요.. 🤔
visiableCells이용해서 상태 바꾸는 코드도 맞는지 고민되구요!

저도 ReactorKit을 잘 사용하지는 못해서 제가 생각하기에 괜찮은 자료 첨부드려요!
https://ios-development.tistory.com/1349
이거 보시고 궁금한 점 있으시면 같이 고민해봐도 좋을 것 같습니다~!

2023-12-31 10:45 UTC, llghdud921 commented on Projects/DesignSystem/Sources/Button/YBPaddingButton.swift
> +            return UIEdgeInsets(top: 7, left: 20, bottom: 7, right: 20)
<img width="165" alt="스크린샷 2023-12-31 오후 7 13 55" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/40068674/f330c401-d0e2-47ae-9e2f-d2ae0a547218"> 
요것도 edge가 피그마랑 다른 것 같아서 보니까 다르네요!

2023-12-31 10:45 UTC, llghdud921 commented on Projects/DesignSystem/Sources/Button/YBPaddingButton.swift
> +public final class YBPaddingButton: UIButton {
요거 padding 만든거 디자인 시스템 어느 버튼 기준으로 만드신건지 여쭤봐도 될까용?

2023-12-31 10:45 UTC, llghdud921 commented on Projects/Features/TravelRegistration/Sources/Presentation/Country/CountryViewController.swift
> +        let searchBar = UISearchBar(frame: CGRect(x: 0, y: 0, width: sc, height: 0))
searchBar icon 저희 아이콘 아닌것같은데.. 
확이 부탁드릴게요 :)

2023-12-31 12:12 UTC, devjoonn commented on Projects/Features/TravelRegistration/Sources/Presentation/Country/CountryViewController.swift
> +                NSAttributedString.Key.font: YBFont.body2.font
![Simulator Screenshot - iPhone 15 Pro - 2023-12-31 at 20 57 19](https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/738427a2-49b7-49a6-94f4-0969067d8711)
![Simulator Screenshot - iPhone 15 Pro - 2023-12-31 at 20 57 03](https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/75eef34c-d012-4841-86fb-dc0b8612ae76)

navigationController에 적용되는 searchBar다 보니 크기가 조금 작아져 body1로 하니까 너무 큰 느낌이라 조금 작은 body2로 적용했습니다!

지금 생각해보니 제 임의대로 변경하지 말고 피그마대로 만들고 QA 때 한 번에 바꾸는 게 좋을 것 같네요!
죄송합니닷..

2023-12-31 12:18 UTC, devjoonn commented on Projects/DesignSystem/Sources/Button/YBPaddingButton.swift
> +public final class YBPaddingButton: UIButton {
넵 맞습니당! Padding 사이즈가 .small 만 지금 피그마에 적용되어 있는 사이즈랑 맞춰서 넣어봤습니다. 근데 피그마 상 디자인과 좀 다르게 나오더라구요 ㅠㅠ 그래서 임의로 피그마와 비슷하게 padding을 조금 더 추가해서 만들게 되었습니다...

<img width="200" alt="스크린샷 2023-12-31 오후 6 11 08" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/a5179a12-4e36-49da-95ef-ff16cdcb5ea8">

이 캡쳐본이 padding과 searchBar 폰트가 피그마와 똑같이 이미지 입니다!


지금 PR 올려져 있는 건 Padding Inset이 .medium에 body2로 적용되어 있습니다.
수정해서 다시 올릴게요!

2023-12-31 12:19 UTC, devjoonn commented on Projects/Features/TravelRegistration/Sources/Presentation/Country/CountryViewController.swift
> +        let searchBar = UISearchBar(frame: CGRect(x: 0, y: 0, width: sc, height: 0))
앗 기본 searchBar icon으로 적용되어있는데 아이콘 새로 추가해서 반영하겠슴당!

2023-12-31 12:20 UTC, devjoonn commented on Projects/DesignSystem/Sources/Button/YBPaddingButton.swift
> +            return UIEdgeInsets(top: 7, left: 20, bottom: 7, right: 20)
이에 관련된 건 밑에 코멘트 남겼습니다 :)

2024-01-01 14:46 UTC, llghdud921 commented on Projects/Features/TravelRegistration/Sources/Presentation/Country/CountryViewController.swift
> +                NSAttributedString.Key.font: YBFont.body2.font
요거 searchBar가 작아져서 알맞는 폰트를 수민님한테 확인받으시면 좋을 것 같습니다 😀
죄송할것은 전혀 아니에요!!

2024-01-06 04:12 UTC, llghdud921 approved these changes

2024-01-06 05:12 UTC, merged