[YB-98] 동행 선택 화면 동행자 추가
YAPP-Github/YeoBee-iOS pull request #22
Opened 2024-01-10 15:39 UTC by devjoonn

## 이슈번호
[YB-98]

## 수정 사항
- DesignSystem YBPaddingButton에 Gradient 넣는 함수 추가했습니다.
- 추후에 연필, 휴지통 버튼 DesignSystem에 추가되면 한 번에 변경할 생각으로 임의로 버튼 만들어두었습니다.
- 최대 동행자 9명 까지 제한만 해둔 상태고 DesignSystem에 Toast 추가되면 설정하겠습니다.

## 화면 (Optional)
| 기본 | 동행있음(추가X) |
| --- | --- | 
|<img width="430" alt="스크린샷 2024-01-11 오전 12 18 30" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/6f2f1103-190b-4bb5-b01f-4b6572b7e645">| <img width="430" alt="스크린샷 2024-01-11 오전 12 19 00" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/0e967b6a-43eb-4a9c-875b-24f676a457f3">|

| 동행없음 | 동행있음(추가O) |
| --- | --- | 
|<img width="430" alt="스크린샷 2024-01-11 오전 12 19 02" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/23b7effd-9f0e-4de2-b7fc-e85a6e562e46">| <img width="430" alt="스크린샷 2024-01-11 오전 12 19 09" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/005d7dc0-d14b-4161-9ce7-50db283b50c5">|

<img width="300" alt="스크린샷 2024-01-11 오전 12 25 12" src="https://github.com/YAPP-Github/YeoBee-iOS/assets/82807263/fd4e39ae-d7e6-4086-8575-ed6fe89543aa">

## target module
- TravelRegistration

## 참고사항
- 동행자 추가 후 이름 변경하는 로직은 다음 PR에 반영해두겠습니당.. 너무 길어졌네요ㅠㅠ
- 혱님과 얘기한 내용으로는 동행 추가 화면 -> 여행 제목 설정 화면 -> 다시 동행 추가 화면으로 돌아왔을 시 기존에 추가했던 동행자들이 남아있는가? 에 대해 그대로 남아 있는게 좋다고 하셨습니다!

2024-01-10 15:52 UTC, uuu1101 requested changes
고생하셨습니다 ! 코멘트 한번 확인해주세용 :)

2024-01-10 15:52 UTC, uuu1101 commented on Projects/DesignSystem/Sources/Button/YBPaddingButton.swift
> +        if gradient {
bool타입의 값은 is로 시작하는게 좋아보입니다 :)

2024-01-10 15:52 UTC, uuu1101 commented on Projects/DesignSystem/Sources/Button/YBPaddingButton.swift
> +            configure(ft: font,
font는 굳이 ft라고 줄여쓸 필요가 없을 것 같아요. 오히려 명확하게 font로 작성 하는게 좋아보입니다 :)

2024-01-10 15:52 UTC, uuu1101 commented on Projects/Features/TravelRegistration/Sources/Presentation/Companion/SubViews/CompanionTableViewCell.swift
> +    }(UIImageView())
요기 혹시 `}()` 로 작성하면 어떻게 되나요?

2024-01-10 15:59 UTC, devjoonn commented on Projects/Features/TravelRegistration/Sources/Presentation/Companion/SubViews/CompanionTableViewCell.swift
> +    }(UIImageView())
아 이건 Then 대신 쓰다가 생긴 습관인데 `}()` 로 작성하면 `Missing argument for parameter #1 in call` 오류가 생겨서 뒤에 생성자를 넣어주어야 하더라구요!

2024-01-10 17:16 UTC, applebuddy reviewed
컨벤션 관련 의견 몇개 남겨봤습니다.
팀 룰 기반으로 가려서 참고부탁드려요~

2024-01-10 17:16 UTC, applebuddy commented on Projects/DesignSystem/Sources/Button/YBPaddingButton.swift
> +        }
P3: 옵셔널 바인딩 간소화가 가능해보여서 의견 드립니다~
```swift
if let gradientLayer {
    layer.insertSublayer(gradientLayer, at: 0)
}
```

2024-01-10 17:16 UTC, applebuddy commented on Projects/Features/TravelRegistration/Sources/Domain/Entities/Companion.swift
> +public struct Companion: Hashable, Equatable {
P3: Hashable 이 자체적으로 Equatable을 준수하는데, 별도로 Equatable을 명시하신 의도가 있으신지 궁금합니다.

2024-01-10 17:16 UTC, applebuddy commented on Projects/Features/TravelRegistration/Sources/Presentation/Companion/CompanionReactor.swift
> +
P3: swift lint 기본 룰에 불필요한 공백 라인 제거를 권장하는게 기억나서 한 줄 제거하면 어떨지 의견드려봅니다~

2024-01-10 17:16 UTC, applebuddy commented on Projects/Features/TravelRegistration/Sources/Presentation/Companion/CompanionViewController.swift
> +            guard let cell = tableView.dequeueReusableCell(withIdentifier: CompanionTableViewCell.identifier, for: indexPath) as? CompanionTableViewCell else { return UITableViewCell() }
P2: 한 줄 글자수가 100이 넘어갈 것 같은데, 이럴때 개행하는것도 고려해보면 좋을 것 같아요. 이것도 swift lint 룰 중에 있던게 기억나서 의견드립니다!

2024-01-10 17:16 UTC, applebuddy commented on Projects/Features/TravelRegistration/Sources/Presentation/Companion/SubViews/CompanionTableViewCell.swift
> +    }(UIImageView())
아래처럼도 가능합니다~
```swift
private let profileImageView: UIImageView = {
  let imageView = UIImageView()
  imageView.backgroundColor = .white
  imageView.layer.cornerRadius = 22
  imageView.clipsToBounds = true
  return imageView
}()
```

2024-01-11 01:35 UTC, devjoonn commented on Projects/Features/TravelRegistration/Sources/Domain/Entities/Companion.swift
> +public struct Companion: Hashable, Equatable {
안녕하세요 경태님! 기존에 사용하던 동등성 비교하는 코드를 비교하면서 추가했습니다. Hashable 자체에서 Equatable을 준수하고 == 메서드를 제공하니 Equatable을 제거하는게 좋을 것 같습니다! 의견 감사합니다 ☺️

2024-01-11 14:20 UTC, llghdud921 approved these changes
고생하셨습니다!!

2024-01-11 14:20 UTC, llghdud921 approved these changes

2024-01-12 14:14 UTC, uuu1101 approved these changes
고생하셨습니다!

2024-01-12 17:54 UTC, merged

2024-01-12 18:24 UTC, applebuddy reviewed
👍👍