네트워크- 로그인 쪽 기본 틀
YAPP-Github/YeoBee-iOS pull request #23
Opened 2024-01-10 15:55 UTC by uuu1101

## 이슈번호
[YB-74]

## 수정 사항
- 모야 이렇게 사용하는게 맞나 싶은데 한번 봐주세용 😅
- 네트워크 모듈 작업을 선행하려고 했으나 API 문서 변경도 있을 예정이라, 지출 쪽은 주석처리 하였습니다.
 로그인쪽 먼저 틀만 잡아두고 로그인 붙이는 작업하면서 네트워크랑 같이 작업 해야할 것 같습니다

2024-01-10 17:22 UTC, applebuddy commented on Projects/Network/Sources/Repository/AuthRepository.swift
> +class AuthRepository: AuthRepositoryInterface {
Q. AuthRepository를 상속하는 클래스가 없다면, final 키워드 붙이는것 어떨까요?

2024-01-10 17:22 UTC, applebuddy commented on Projects/Network/Sources/Service/ExpenseService.swift
> +            if let unitId = unitId { params["unitId"] = unitId }
P2: 옵셔널 바인딩 간소화 가능해보입니다. 🙇🏻‍♂️




```swift
            if let type { params["type"] = type.rawValue }
            if let date { params["date"] = ISO8601DateFormatter().string(from: date) }
            if let method { params["method"] = method.rawValue }
            if let unitId { params["unitId"] = unitId }
```

2024-01-10 17:22 UTC, applebuddy commented on Projects/Network/Sources/Service/ExpenseService.swift
> +    var headers: [String : String]? {
P2: 아래 처럼 수정해서 다른 곳과 맞추면 좋을 것 같습니다. (콜론 앞 공백 제거)
```swift
var headers: [String: String]? {
// ...
}
```

2024-01-10 17:22 UTC, applebuddy commented on Projects/Network/Sources/Service/ExpenseService.swift
> +
P2: 파일 끝 공백, 불필요 공백 제거해도 좋을 것 같습니다. (swift lint 기본 룰 기반으로 의견 드립니다.)

2024-01-11 02:29 UTC, uuu1101 commented
@applebuddy 경태님 피드백 감사합니다 :)

2024-01-11 14:29 UTC, llghdud921 requested changes
리뷰 남겼습니다~!

고생많으셨습니다!

2024-01-11 14:29 UTC, llghdud921 commented on Projects/Network/Sources/Repository/AuthRepository.swift
> +
불편하네요..

2024-01-11 14:29 UTC, llghdud921 commented on Projects/Network/Sources/Service/ExpenseService.swift
> +                   unitId: Int? = nil)
들여쓰기 불편하네요..

2024-01-11 14:29 UTC, llghdud921 commented on Projects/Network/Sources/Service/ExpenseService.swift
> +    var baseURL: URL { return URL(string: "https://api.yeobee.me")!}
끼야아아아아아 우리 api!!!!!!!

2024-01-11 14:29 UTC, llghdud921 commented on Projects/Network/Sources/Service/ExpenseService.swift
> +            if let type { params["type"] = type.rawValue }
오.. 옵셔널 처리가 안되는군요!
api 작동되면 테스트해봐야겠네요!!

2024-01-12 14:13 UTC, uuu1101 commented on Projects/Network/Sources/Service/ExpenseService.swift
> +    var baseURL: URL { return URL(string: "https://api.yeobee.me")!}
아ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ

2024-01-12 18:31 UTC, applebuddy commented on Projects/Network/Sources/Service/ExpenseService.swift
> +                   unitId: Int? = nil)
Q. PaymentMethod 타입이 배열 형태는 아닌데, paymentMethods로 레이블 명명을 하신 이유가 궁금합니다!

2024-01-13 05:39 UTC, uuu1101 commented on Projects/Network/Sources/Service/ExpenseService.swift
> +                   unitId: Int? = nil)
처음에 타입을 PaymentMethods로 명명했다가 수정하면서 요부분 같이 수정하는 것을 빼먹은것 같네용

2024-01-13 06:11 UTC, llghdud921 approved these changes

2024-01-13 10:14 UTC, applebuddy approved these changes
LGTM

2024-01-13 11:03 UTC, merged