[YB-122] 토큰 분기 처리 및 스플래시 화면을 추가했어요.
YAPP-Github/YeoBee-iOS pull request #42
Opened 2024-02-13 16:20 UTC by uuu1101

## 이슈번호
[YB-122](https://yeobee.atlassian.net/jira/software/projects/YB/boards/1?selectedIssue=YB-122)

## 수정 사항
- 코드는 일단 맘에 안들지만.. 기능 구현이 좀 급해서 PR올려요

## 화면 (Optional)
-온보딩이 끝나기전 종료 후 진입시

https://github.com/YAPP-Github/YeoBee-iOS/assets/49808034/705f800a-4d3f-4bdc-8826-3991f0958e41
- 자동 로그인

https://github.com/YAPP-Github/YeoBee-iOS/assets/49808034/19479167-3456-4e99-8055-6ca403882e22

2024-02-13 18:03 UTC, llghdud921 requested changes
수정 요청사항 남겼습니다!

스플래시 까만 화면 현상은 내일 저도 살펴보겠습니다!!
고생하셨습니다~!

2024-02-13 18:03 UTC, llghdud921 commented on Projects/YeoBee/Sources/AppDelegate.swift
> +            let isTokenExpiring = try await tokenRepository.isTokenExpiring()
리프레시 토큰까지 만료된 상황이라면 키체인에서 토큰 정보 제거해줘야할 것 같습니다!

2024-02-13 18:23 UTC, applebuddy approved these changes
커피스는 스플래시 없는데.. 굿이네요 👍

2024-02-13 18:23 UTC, applebuddy commented on Projects/YeoBee/Sources/AppDelegate.swift
> +        Thread.sleep(forTimeInterval: 1.5)
Q. 별도 데이터 로드를 위한 목적이 아닌, 런치스크린 보여주는 시간을 사양을 정해서 1.5초로 지정하신것 맞을까요? 🙇🏻‍♂️

2024-02-14 00:43 UTC, uuu1101 commented on Projects/YeoBee/Sources/AppDelegate.swift
> +        Thread.sleep(forTimeInterval: 1.5)
네 맞습니다.

2024-02-14 00:43 UTC, uuu1101 commented on Projects/YeoBee/Sources/AppDelegate.swift
> +            let isTokenExpiring = try await tokenRepository.isTokenExpiring()
헐헐 그러네요, 로그아웃만 생각해서 요기도 추가할게요!

2024-02-14 03:31 UTC, llghdud921 approved these changes
🙇‍♀️

2024-02-14 06:36 UTC, merged